### ISSUE TITLE
[Feature request] Animations

### ISSUE THREAD

**Issue by Lato-o** [Yanndroid/DualWallpaper#21]
Hi, it would be nice if you could add a "transition" between lock screen and homescreen wallpaper (if they are different) like a fade out/ fade in.
Thanks for your work 🙏

**Comment by Yanndroid** [comment]
That's nothing an app can do, it's handled by the system and can't be customized.

**Comment by Lato-o** [comment]
This app can do it but your app and this app won't work the same i think... 
Thanks for your answer.
Have a great day
https://github.com/cvzi/darkmodewallpaper

**Comment by Yanndroid** [comment]
I see what you mean. The difference is that he's doing it with a Live Wallpaper.
I had this option too in the past, but had a ton of issues (especially with the screen rotation). So I decided to drop it. It also consumes a lot more power, since it's basically a video, constantly playing in the background.
I don't think I'll implement this again.
